default_platform(:android)

platform :android do
  desc "Release a new version to the Google Play"
  lane :release do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(
        track: "beta"
    )
  end
end
