name: Build

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      TERM: dumb
      SIGNING_CONFIG_RELEASE_KEYSTORE_PWD: ${{ secrets.SIGNING_CONFIG_RELEASE_KEYSTORE_PWD }}
      SIGNING_CONFIG_RELEASE_KEY_PWD: ${{ secrets.SIGNING_CONFIG_RELEASE_KEY_PWD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Decrypt secrets
        run: release/signing-setup.sh $ENCRYPT_KEY
        env:
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}

      - name: Check spotless
        run: ./gradlew spotlessCheck --no-configuration-cache

      - name: Check lint
        run: ./gradlew :app:lintRelease

      - name: Build all build type and flavor permutations
        run: ./gradlew assemble

      - name: Run local tests
        run: ./gradlew test

      - name: Clean secrets
        if: always()
        run: release/signing-cleanup.sh