name: Update libraries.json file

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0 1 * *' # On the first day of every month

jobs:
  libraries:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download libraries json file
        run: wget ${{ secrets.LIBRARIES_ENDPOINT }} -q -O app/src/main/res/raw/libraries.json

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_PR_TOKEN }}
          branch: "auto_pr/update-libraries"
          title: "Auto PR: Update libraries.json"
          body: "Automatic PR to update list of libraries to scan for in Detective Droid."
