name: Release to Play Store

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      TERM: dumb
      SIGNING_CONFIG_RELEASE_KEYSTORE_PWD: ${{ secrets.SIGNING_CONFIG_RELEASE_KEYSTORE_PWD }}
      SIGNING_CONFIG_RELEASE_KEY_PWD: ${{ secrets.SIGNING_CONFIG_RELEASE_KEY_PWD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup Ruby for Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Decrypt secrets
        run: release/signing-setup.sh $ENCRYPT_KEY
        env:
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}

      - name: Release to Play Store Beta
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'release'
          verbose: true

      - name: Clean secrets
        if: always()
        run: release/signing-cleanup.sh